"""Add direct customer column

Revision ID: 16882ad1af0b
Revises: 941ea5c40caf
Create Date: 2025-04-13 11:16:48.451995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16882ad1af0b"
down_revision: Union[str, None] = "941ea5c40caf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("domain", sa.String(), nullable=True))
    op.add_column("users", sa.Column("is_direct", sa.Boolean(), server_default="true", nullable=False))
    op.create_unique_constraint(None, "users", ["domain"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "is_direct")
    op.drop_column("users", "domain")
    # ### end Alembic commands ###
