"""Add app client table

Revision ID: 5b08e610f683
Revises: 16882ad1af0b
Create Date: 2025-04-13 12:00:53.009203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b08e610f683"
down_revision: Union[str, None] = "16882ad1af0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login_redirect_url", sa.String(), nullable=True),
        sa.Column("logout_redirect_url", sa.String(), nullable=True),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("client_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
        sa.UniqueConstraint("domain"),
    )
    op.drop_constraint("users_domain_key", "users", type_="unique")
    op.drop_column("users", "domain")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("domain", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint("users_domain_key", "users", ["domain"])
    op.drop_table("clients")
    # ### end Alembic commands ###
