"""Add M2M relationship for Client and User

Revision ID: dc44f0ef61f2
Revises: 5b08e610f683
Create Date: 2025-04-13 19:11:33.244347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc44f0ef61f2"
down_revision: Union[str, None] = "5b08e610f683"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_users",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("client_id", "user_id"),
    )
    op.add_column("clients", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "clients", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clients", type_="foreignkey")
    op.drop_column("clients", "owner_id")
    op.drop_table("client_users")
    # ### end Alembic commands ###
