stages:
  - publish-images


variables:
  BACKEND_TAG: "backend-${CI_COMMIT_SHORT_SHA}"
  FRONTEND_TAG: "frontend-${CI_COMMIT_SHORT_SHA}"
  DOCKER_HOST: tcp://docker:2375

publish-images:
  stage: publish-images
  image:
    name: amazon/aws-cli
    entrypoint: [""]

  services:
    - docker:dind

  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version

  script:
    - sh ci/build-and-push-images.sh
  only:
    - main

  artifacts:
    paths:
      - build-info.json
