stages:
  - publish-images
  - deploy

variables:
  BACKEND_TAG: "backend-${CI_COMMIT_SHORT_SHA}"
  FRONTEND_TAG: "frontend-${CI_COMMIT_SHORT_SHA}"
  DOCKER_HOST: tcp://docker:2375

publish-images:
  stage: publish-images
  image:
    name: amazon/aws-cli
    entrypoint: [""]

  services:
    - docker:dind

  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version

  script:
    - sh ci/build-and-push-images.sh
  only:
    - main

  artifacts:
    reports:
      dotenv: vars.env
    paths:
      - build-info.json

.terraform-job:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  stage: deploy
  before_script:
    - terraform --version
    - cd ci/terraform
    - terraform init
  only:
    - main

validate:
  extends: .terraform-job
  script:
    - terraform validate
  dependencies:
    - publish-images

plan:
  extends: .terraform-job
  script:
    - terraform plan
  dependencies:
    - publish-images
    - validate

apply:
  extends: .terraform-job
  script:
    - terraform apply -auto-approve
  dependencies:
    - plan
    - publish-images
  when: manual
  only:
    - main
